Principal Component Analysis Name - Devanand Saysing Vasave PRN - 1930331245065

In [2]:
from numpy import array
from numpy import mean
from numpy import cov
from numpy.linalg import eig
import pandas as pd

A = array([[1.5,2.9],
           [0.6,0.2],
           [2.2,2.9],
           [1.4,3.1],
           [3.1,3.0],
           [2.3,2.7],
           [2,1.6],
           [1,2.1],
           [1.5,1.6],
           [1.1,0.9]])
print(A)

[[1.5 2.9]
 [0.6 0.2]
 [2.2 2.9]
 [1.4 3.1]
 [3.1 3. ]
 [2.3 2.7]
 [2.  1.6]
 [1.  2.1]
 [1.5 1.6]
 [1.1 0.9]]


In [3]:
M = mean(A.T, axis=1)
print(M)

[1.67 2.1 ]


In [4]:
C = A - M
print(C)

[[-1.7000000e-01  8.0000000e-01]
 [-1.0700000e+00 -1.9000000e+00]
 [ 5.3000000e-01  8.0000000e-01]
 [-2.7000000e-01  1.0000000e+00]
 [ 1.4300000e+00  9.0000000e-01]
 [ 6.3000000e-01  6.0000000e-01]
 [ 3.3000000e-01 -5.0000000e-01]
 [-6.7000000e-01 -4.4408921e-16]
 [-1.7000000e-01 -5.0000000e-01]
 [-5.7000000e-01 -1.2000000e+00]]


In [6]:
V = cov(C.T)
print(V)

[[0.54233333 0.48      ]
 [0.48       1.        ]]


In [7]:

values, vectors = eig(V)
print(vectors)
print(values)


[[-0.84567577 -0.533697  ]
 [ 0.533697   -0.84567577]]
[0.23941043 1.3029229 ]


In [8]:
P = vectors.T.dot(C.T)
print(P.T)

[[ 0.57072248 -0.58581213]
 [-0.10915122  2.17783976]
 [-0.02125056 -0.95940003]
 [ 0.76202946 -0.70157758]
 [-0.72898906 -1.5242949 ]
 [-0.21255754 -0.84363457]
 [-0.5459215   0.24671788]
 [ 0.56660277  0.35757699]
 [-0.12308362  0.51356638]
 [-0.15840121  1.31901822]]


In [9]:
from sklearn.decomposition import PCA

pca = PCA(2)
pca.fit_transform(A)
print(pca.components_)
print(pca.explained_variance_)

B = pca.transform(A)
print(B)


[[-0.533697   -0.84567577]
 [-0.84567577  0.533697  ]]
[1.3029229  0.23941043]
[[-0.58581213  0.57072248]
 [ 2.17783976 -0.10915122]
 [-0.95940003 -0.02125056]
 [-0.70157758  0.76202946]
 [-1.5242949  -0.72898906]
 [-0.84363457 -0.21255754]
 [ 0.24671788 -0.5459215 ]
 [ 0.35757699  0.56660277]
 [ 0.51356638 -0.12308362]
 [ 1.31901822 -0.15840121]]
